application: phone
Init: True
Process: True
Thread: True
screen-size: [240, 320]
icon-size: [40, 40]
module-settings:
  mic: external
  speaker: external
screen-modes: 
  1:
    1: [2, 2.5]
    2: [3.5, 2.5]
    3: [5, 2.5]
    4: [2, 3.75]
    5: [3.5, 3.75]
    6: [5, 3.75]
    7: [2, 5]
    8: [3.5, 5]
    9: [5, 5]
    0: [3.5, 6.25]
    star: [2, 6.25]
    hash: [5, 6.25]
    call: [3.5, 7.5]
    delete: [5.5, 7.5]
    go_back: [1.5, 7.5]
  2:
    hangup: [3.5, 7.5]
  3: 
    call: [2.5, 7]
    hangup: [4.5, 7]
